# Generated by Django 5.2.8 on 2025-11-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=255)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('requirements', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('salary', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'portal_internship',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PortalJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('requirements', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('salary', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'portal_job',
                'managed': True,
            },
        ),
    ]
