# Generated by Django 5.2.8 on 2025-11-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalinternship',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
