# Generated by Django 5.2.8 on 2025-11-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_add_location_to_portal_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaljob',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
