# Generated by Django 5.2.8 on 2025-11-30 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_portaljob_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('education', models.CharField(choices=[('high_school', 'High School'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('postgraduate', 'Postgraduate')], max_length=100)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('skills', models.TextField(blank=True)),
                ('preferred_role', models.CharField(blank=True, max_length=255)),
                ('availability', models.CharField(choices=[('full_time', 'Full-time (40 hours/week)'), ('part_time', 'Part-time (20-30 hours/week)'), ('flexible', 'Flexible')], max_length=50)),
                ('duration', models.CharField(blank=True, choices=[('3_months', '3 Months'), ('6_months', '6 Months'), ('9_months', '9 Months'), ('12_months', '12 Months')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='applications/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('cover_letter', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.portalinternship')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('education', models.CharField(choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD')], max_length=100)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.CharField(choices=[('0', '0 years (Entry Level)'), ('1-2', '1-2 years'), ('3-5', '3-5 years'), ('6-10', '6-10 years'), ('10+', '10+ years')], max_length=50)),
                ('current_position', models.CharField(blank=True, max_length=255)),
                ('current_company', models.CharField(blank=True, max_length=255)),
                ('skills', models.TextField(blank=True)),
                ('preferred_role', models.CharField(blank=True, max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance')], max_length=50)),
                ('salary_expectation', models.CharField(blank=True, max_length=100)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('work_authorization', models.CharField(choices=[('us_citizen', 'US Citizen'), ('permanent_resident', 'Permanent Resident'), ('h1b', 'H1B Visa'), ('tn_visa', 'TN Visa'), ('other_visa', 'Other Visa'), ('need_sponsorship', 'Require Sponsorship')], max_length=100)),
                ('resume', models.FileField(upload_to='applications/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('cover_letter', models.TextField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.portaljob')),
            ],
        ),
    ]
