# Generated by Django 5.2.5 on 2025-12-01 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_emailconfiguration'),
        ('portal', '0004_internshipapplication_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalinternship',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='portalinternship',
            name='email',
        ),
        migrations.RemoveField(
            model_name='portaljob',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='portaljob',
            name='email',
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
        migrations.AddField(
            model_name='portalinternship',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
        migrations.AddField(
            model_name='portaljob',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
    ]
