# Generated by Django 5.2.5 on 2025-12-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_portalinternship_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalinternship',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='portaljob',
            name='supplier',
        ),
        migrations.AddField(
            model_name='portalinternship',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='portalinternship',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='portaljob',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='portaljob',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
