# Generated by Django 5.2.5 on 2025-12-01 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_emailconfiguration'),
        ('portal', '0006_remove_portalinternship_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalinternship',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='app.supplier'),
        ),
        migrations.AddField(
            model_name='portaljob',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='app.supplier'),
        ),
    ]
