# Generated by Django 5.2.5 on 2025-12-02 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_portalinternship_supplier_portaljob_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='education',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='major',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='preferred_role',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='availability_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='current_company',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='current_position',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='major',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='preferred_role',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='salary_expectation',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='work_authorization',
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='additional_attachment',
            field=models.FileField(blank=True, help_text='Max size: 5MB. Accepted formats: PDF, DOCX, DOC, PNG, JPG', null=True, upload_to='applications/attachments/'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='additional_questions',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='city_of_study',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='currently_studying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='field_of_study',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='internships',
            field=models.TextField(blank=True, help_text='Details of internships (optional)'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='message_to_manager',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='status',
            field=models.CharField(choices=[('fresher', 'Fresher'), ('experienced', 'Experienced')], default='fresher', max_length=50),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='study_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='study_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='work_experiences',
            field=models.JSONField(blank=True, default=list, help_text='Array of work experience entries'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='additional_attachment',
            field=models.FileField(blank=True, help_text='Max size: 5MB. Accepted formats: PDF, DOCX, DOC, PNG, JPG', null=True, upload_to='applications/attachments/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='city_of_study',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='currently_studying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='field_of_study',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='message_to_manager',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='screening_questions',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('fresher', 'Fresher'), ('experienced', 'Experienced')], default='fresher', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='study_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='study_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='work_experiences',
            field=models.JSONField(blank=True, default=list, help_text='Array of work experience entries (required for experienced applicants)'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='resume',
            field=models.FileField(help_text='Max size: 2MB. Accepted formats: PDF, DOCX, DOC', upload_to='applications/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='skills',
            field=models.TextField(blank=True, help_text='Enter skills separated by commas or as tags'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(help_text='Max size: 2MB. Accepted formats: PDF, DOCX, DOC', upload_to='applications/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='skills',
            field=models.TextField(blank=True, help_text='Enter skills separated by commas or as tags'),
        ),
    ]
