# Generated by Django 6.0 on 2025-12-09 21:34

import django.core.validators
import utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_internshipapplication_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalinternship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.paths.company_internship_upload),
        ),
        migrations.AddField(
            model_name='portalinternship',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portaljob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.paths.company_job_upload),
        ),
        migrations.AddField(
            model_name='portaljob',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='additional_attachment',
            field=models.FileField(blank=True, help_text='Max size: 5MB. Accepted formats: PDF, DOCX, DOC, PNG, JPG', null=True, upload_to=utils.paths.company_application_upload),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='resume',
            field=models.FileField(help_text='Max size: 2MB. Accepted formats: PDF, DOCX, DOC', upload_to=utils.paths.company_application_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='additional_attachment',
            field=models.FileField(blank=True, help_text='Max size: 5MB. Accepted formats: PDF, DOCX, DOC, PNG, JPG', null=True, upload_to=utils.paths.company_application_upload),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(help_text='Max size: 2MB. Accepted formats: PDF, DOCX, DOC', upload_to=utils.paths.company_application_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
