# Generated by Django 6.0 on 2025-12-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_portalinternship_image_portalinternship_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaljob',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
