# Generated by Django 6.0 on 2025-12-10 19:38

import django.core.validators
import utils.paths
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_fix_portaljob_missing_image_url'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('fresher', 'Fresher'), ('experienced', 'Experienced')], default='fresher', max_length=50)),
                ('resume', models.FileField(help_text='Max size: 2MB. Accepted formats: PDF, DOCX, DOC', upload_to=utils.paths.company_application_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('school_name', models.CharField(blank=True, default='', max_length=255)),
                ('city_of_study', models.CharField(blank=True, default='', max_length=255)),
                ('degree', models.CharField(blank=True, default='', max_length=255)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=255)),
                ('study_from_date', models.DateField(blank=True, null=True)),
                ('study_to_date', models.DateField(blank=True, null=True)),
                ('currently_studying', models.BooleanField(default=False)),
                ('skills', models.TextField(blank=True, help_text='Enter skills separated by commas or as tags')),
                ('linkedin_profile', models.URLField(blank=True)),
                ('internships', models.TextField(blank=True, help_text='Details of internships (optional)')),
                ('work_experiences', models.JSONField(blank=True, default=list, help_text='Array of work experience entries')),
                ('additional_questions', models.TextField(blank=True, max_length=2000)),
                ('message_to_manager', models.TextField(blank=True, max_length=2000)),
                ('additional_attachment', models.FileField(blank=True, help_text='Max size: 5MB. Accepted formats: PDF, DOCX, DOC, PNG, JPG', null=True, upload_to=utils.paths.company_application_upload)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.portalinternship')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supplier')),
            ],
        ),
    ]
