services:
  - type: web
    name: cianext
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requir.txt
    startCommand: gunicorn proj.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.wrezjfnkxqcjvbcpuhcr:aFdtupVD1S5HrbbD@aws-1-ap-south-1.pooler.supabase.com:5432/postgres
      - key: PYTHON_VERSION
        value: 3.13.5
