# Generated by Django 5.2.5 on 2025-09-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='gstno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product9',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_image10',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/product_images/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_image5',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/product_images/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_image6',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/product_images/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_image7',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/product_images/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_image8',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/product_images/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_image9',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/product_images/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
