# Generated by Django 5.2.5 on 2025-09-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_supplier_image_remove_supplier_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photogallery/images/'),
        ),
    ]
