# Generated by Django 5.2.5 on 2025-09-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_supplier_image_url_supplier_logo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='image',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='person_image',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product_image1',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product_image10',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product_image2',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product_image3',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product_image4',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product_image5',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product_image6',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product_image7',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product_image8',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product_image9',
        ),
    ]
