# Generated by Django 5.2.5 on 2025-09-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_photogallery_image_url_alter_photogallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
