# Generated by Django 5.2.5 on 2025-09-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_announcement_referral_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexHover',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='index_hover/images/')),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
