# Generated by Django 5.2.5 on 2025-10-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_suppliereditrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliereditrequest',
            name='requested_data',
        ),
        migrations.AddField(
            model_name='suppliereditrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='suppliereditrequest',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
