# Generated by Django 5.2.5 on 2025-10-20 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20251020_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliereditrequest',
            name='message',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='SupplierListingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('founder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.TextField(blank=True, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_category1', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_category2', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_category3', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person_image_url', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('product1', models.CharField(blank=True, max_length=255, null=True)),
                ('product2', models.CharField(blank=True, max_length=255, null=True)),
                ('product3', models.CharField(blank=True, max_length=255, null=True)),
                ('product4', models.CharField(blank=True, max_length=255, null=True)),
                ('product5', models.CharField(blank=True, max_length=255, null=True)),
                ('product6', models.CharField(blank=True, max_length=255, null=True)),
                ('product7', models.CharField(blank=True, max_length=255, null=True)),
                ('product8', models.CharField(blank=True, max_length=255, null=True)),
                ('product9', models.CharField(blank=True, max_length=255, null=True)),
                ('product10', models.CharField(blank=True, max_length=255, null=True)),
                ('door_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('gstno', models.CharField(blank=True, max_length=15, null=True)),
                ('instagram', models.TextField(blank=True, null=True)),
                ('facebook', models.TextField(blank=True, null=True)),
                ('total_employees', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_listing_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
