# Generated by Django 5.2.5 on 2025-10-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_contactinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspapergallery',
            name='date',
            field=models.DateField(blank=True, help_text='Manually entered date for the newspaper cutting', null=True),
        ),
    ]
