# Generated by Django 5.2.5 on 2025-10-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_newspapergallery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(blank=True, help_text='Our mission statement', null=True)),
                ('story', models.TextField(blank=True, help_text='Our story content', null=True)),
                ('member_companies', models.PositiveIntegerField(default=0, help_text='Number of member companies')),
                ('industrial_sectors', models.PositiveIntegerField(default=0, help_text='Number of industrial sectors')),
                ('established_year', models.PositiveIntegerField(default=2020, help_text='Year established')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
