# Generated by Django 5.2.5 on 2025-11-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadership',
            options={'ordering': ['dis_pos', '-created_at']},
        ),
        migrations.AddField(
            model_name='leadership',
            name='dis_pos',
            field=models.PositiveIntegerField(default=0, help_text='Display position for ordering leadership cards'),
        ),
    ]
