# Generated by Django 5.2.8 on 2025-11-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('host_user', models.EmailField(default='cianextcbe@gmail.com', max_length=254)),
                ('host_password', models.CharField(default='cwgk azyb oxsp pfih', max_length=255)),
                ('default_from_email', models.EmailField(default='cianextcbe@gmail.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
    ]
