# Generated by Django 5.2.5 on 2025-12-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_emailconfiguration'),
        ('app', '0022_supplierreview'),
    ]

    operations = [
    ]
