# Generated by Django 5.2.5 on 2025-12-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_supplier_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexHover',
        ),
        migrations.DeleteModel(
            name='InternshipApplication',
        ),
    ]
