# Generated by Django 6.0 on 2025-12-09 21:34

import utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_indexhover_internshipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image1_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image2_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image3_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.paths.supplier_logo_upload),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=utils.paths.flash_upload),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=utils.paths.flash_upload),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=utils.paths.flash_upload),
        ),
        migrations.AlterField(
            model_name='bookshowcase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.paths.book_upload),
        ),
        migrations.AlterField(
            model_name='newspapergallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.paths.newspaper_upload),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.paths.photo_gallery_upload),
        ),
    ]
