# Generated by Django 6.0 on 2025-12-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_announcement_image1_url_announcement_image2_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='twitter',
            field=models.URLField(blank=True, help_text='Twitter profile URL', max_length=500, null=True),
        ),
    ]
