# Generated by Django 5.2.5 on 2025-12-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Flash Announcement', 'verbose_name_plural': 'Flash Announcements'},
        ),
    ]
