# Generated by Django 5.2.5 on 2025-12-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_alter_announcement_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='url',
        ),
    ]
